<script setup>
const repository = 'https://github.com/MCTranslate/MCHive'
</script>

<template>
  <div class="contribute-page">
    <nav class="breadcrumb" aria-label="面包屑"><RouterLink to="/">首页</RouterLink><span>/</span><span>贡献指南</span></nav>
    <header class="page-heading"><span class="eyebrow">COMMUNITY CONTRIBUTIONS</span><h1>让开服知识更容易找到。</h1><p>补充一篇教程、完善一份插件资料，或修正文档中的错误，都能帮助下一位服主少走弯路。</p><a class="primary-action" :href="repository + '/issues'" target="_blank" rel="noreferrer">提出问题或建议 <span aria-hidden="true">↗</span></a></header>
    <section class="contribution-types" aria-label="贡献方式">
      <article><span class="step">01</span><h2>新增教程</h2><p>在 <code>content/guides/</code> 新建 Markdown 文件，并在 <code>data/guides.json</code> 添加标题、简介和标签。</p><a :href="repository + '/tree/master/content/guides'" target="_blank" rel="noreferrer">查看现有教程 <span aria-hidden="true">↗</span></a></article>
      <article><span class="step">02</span><h2>补充插件资料</h2><p>复制 <code>content/plugins/_template/</code> 作为起点，在插件索引中登记元数据和内容章节。</p><a :href="repository + '/tree/master/content/plugins/_template'" target="_blank" rel="noreferrer">查看插件模板 <span aria-hidden="true">↗</span></a></article>
      <article><span class="step">03</span><h2>贡献汉化文件</h2><p>将可直接使用的语言或配置文件放入对应插件下载目录，并在插件索引中列出文件名与用途。</p><a :href="repository + '/tree/master/public/downloads/plugins'" target="_blank" rel="noreferrer">查看下载文件 <span aria-hidden="true">↗</span></a></article>
    </section>
    <section class="workflow"><div><span class="eyebrow">PULL REQUEST FLOW</span><h2>提交前，先核对这些内容</h2></div><ol><li>确认内容针对明确的服务端或插件版本；不确定时写明验证范围。</li><li>保留上游项目名称、作者和许可信息，不把示例文件描述为官方文件。</li><li>检查 Markdown 链接、代码围栏和下载路径，避免泄露服务器或玩家隐私。</li><li>在本地运行 <code>npm run build</code>，再通过 GitHub Pull Request 提交。</li></ol></section>
    <footer class="contribute-footer"><span>内容维护以准确、可复现和来源清晰为优先。</span><a :href="repository + '/blob/master/CONTRIBUTING.md'" target="_blank" rel="noreferrer">阅读仓库贡献规范 <span aria-hidden="true">↗</span></a></footer>
  </div>
</template>

<style scoped>
.contribute-page{width:min(1000px,calc(100% - 64px));margin:auto;padding:28px 0 72px}.breadcrumb{display:flex;gap:9px;color:var(--text-muted);font-size:11px}.breadcrumb a{color:inherit;text-decoration:none}.page-heading{max-width:720px;margin:64px 0 54px}.eyebrow{color:var(--accent-strong);font:10px var(--font-mono);letter-spacing:1px}.page-heading h1{margin-top:12px;font-size:clamp(32px,4vw,46px);line-height:1.25;font-weight:680}.page-heading p{max-width:610px;margin-top:14px;color:var(--text-muted);font-size:15px;line-height:1.8}.primary-action{display:inline-flex;gap:18px;align-items:center;margin-top:23px;padding:11px 15px;border-radius:5px;background:var(--accent);color:var(--button-text);font-weight:650;text-decoration:none;transition:background .16s}.primary-action:hover{background:var(--accent-hover)}.contribution-types{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border-top:1px solid var(--border-strong);border-bottom:1px solid var(--border-strong)}.contribution-types article{min-width:0;padding:23px 21px 26px;border-right:1px solid var(--border)}.contribution-types article:first-child{padding-left:0}.contribution-types article:last-child{border-right:0}.step{color:var(--accent-strong);font:11px var(--font-mono)}.contribution-types h2,.workflow h2{margin-top:18px;font-size:17px;font-weight:650}.contribution-types p{min-height:94px;margin-top:9px;color:var(--text-muted);font-size:12px;line-height:1.8}.contribute-page code{padding:2px 5px;border:1px solid var(--border);border-radius:3px;background:var(--surface);color:var(--accent-strong);font:11px var(--font-mono);overflow-wrap:anywhere}.contribution-types a,.contribute-footer a{color:var(--accent-strong);font-size:12px;text-decoration:none}.workflow{display:grid;grid-template-columns:.8fr 1.2fr;gap:50px;padding:47px 0;border-bottom:1px solid var(--border)}.workflow h2{margin-top:9px}.workflow ol{margin:0;padding-left:20px;color:var(--text-secondary);font-size:12px;line-height:1.9}.workflow li+li{margin-top:8px}.contribute-footer{display:flex;justify-content:space-between;gap:20px;padding-top:20px;color:var(--text-muted);font-size:11px}@media(max-width:700px){.contribute-page{width:calc(100% - 36px);padding-top:19px}.page-heading{margin:42px 0 38px}.page-heading h1{font-size:33px}.page-heading p{font-size:13px}.contribution-types{grid-template-columns:1fr}.contribution-types article,.contribution-types article:first-child{padding:19px 0;border-right:0;border-bottom:1px solid var(--border)}.contribution-types article:last-child{border-bottom:0}.contribution-types h2{margin-top:10px}.contribution-types p{min-height:0;margin-bottom:10px}.workflow{grid-template-columns:1fr;gap:18px;padding:32px 0}.contribute-footer{flex-direction:column;gap:9px}}
</style>
